version: '3.1'

services:
  # ZOOKEEPER
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - bigdata-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 524288000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 524288000
    depends_on:
      - zookeeper
    networks:
      - bigdata-net


  # NIFI
  nifi:
    image: apache/nifi:1.28.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_HOST: "0.0.0.0"
      NIFI_WEB_HTTPS_PORT: "8443"
      NIFI_WEB_PROXY_HOST: "localhost:8443"
    depends_on:
      - kafka
    networks:
      - bigdata-net

  # SPARK MASTER
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: bash -c "/opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/*" 
    environment:
      SPARK_MODE: master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./ivy_cache:/home/spark/.ivy2
    networks:
      - bigdata-net

  # SPARK WORKER
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/*" 
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: "2"
    depends_on:
      - spark-master
    networks:
      - bigdata-net

  # POSTGRESQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - bigdata-net

  # PGADMIN (optionnel)
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - bigdata-net
  #   volumes:
  #     - ./pgadmin_data:/var/lib/pgadmin

  # GRAFANA (optionnel)
  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     GF_SECURITY_ADMIN_USER: admin
  #     GF_SECURITY_ADMIN_PASSWORD: admin
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./grafana_data:/var/lib/grafana
  #   networks:
  #     - bigdata-net

# RÃ©seau commun
networks:
  bigdata-net:
    driver: bridge
